[package]
name = "roverd"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = "1.0.210"

utoipa = { version = "5.1.1", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "8.0.2", features = ["actix-web"] }

