[package]
name = "rovervalidate"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"

[dependencies]
regex = "1.11.1"
serde = "1.0.214"
serde_derive = "1.0.214"
serde_json = "1.0.132"
serde_yaml = "0.9.34"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
