name: build-and-upload

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-and-upload:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: make build

    - name: Set REPO_NAME environment variable
      run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
    
    - name: Zip binary and service.yaml
      run: zip roverd.zip -r ./targer/release/roverd

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ env.REPO_NAME }}.zip
        asset_name: ${{ env.REPO_NAME }}.zip
        asset_content_type: application/zip
